---

## Required Pacakges Installation ##

- name: install curl
  yum:
    name: ['wget', 'curl', 'tar', 'zip', 'python-psycopg2', 'bison.x86_64', 'flex.x86_64', 'readline.x86_64', 'readline-devel.x86_64', 'zlib.x86_64', 'zlib-devel.x86_64', 'gcc.x86_64', 'openssl-devel.x86_64'] 
    state: present

## Add Postgres User

- name: Ensure group "postgres" exists
  group:
    name: postgres
    state: present


- name: Add the user 'postgres' a primary group of 'postgres'
  user:
    name: postgres
    comment: DB PostgreSQL
    group: postgres   
    shell: /bin/bash

    
## Create Directories
- name: create directory postgres & postgres_log
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0750
  with_items:
    - /postgres
    - /postgres_log
    - /postgres/admin
    - /postgres/admin/config
    - /postgres/admin/home
    - /postgres/admin/home/.ssh
    - /postgres/admin/log
    - /postgres/admin/scripts
    - /postgres/install
    - /postgres/system
    - /postgres/system/pgsql105
     

- name: create directory pgdata & pgbackup
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  with_items:
    - /pgdata
    - /pgbackup
    - /pgbackup/backup01
    - /pgbackup/backup01/WAL
    - /pgdata/pgdata01
    - /pgdata/temp

- name: change  user 'postgres' home
  user:
    name: postgres
    home: /postgres/admin/home

    
## Create Keys for postgres user

- name: generate shh keys
  become: yes
  become_user: postgres
  command: ssh-keygen -b 2048 -q -t rsa -f /postgres/admin/home/.ssh/id_rsa -C "" -N ""

- name: Deploy SSH Key for postgres user
  authorized_key: 
     user: postgres
     key: "{{ lookup('file', '/postgres/admin/home/.ssh/id_rsa.pub') }}"
     state: present
     
## Add /etc/hosts file entries
- name: Update /etc/hosts from inventory
  lineinfile: dest=/etc/hosts regexp='.*{{item}}$' line='{{hostvars[item].ansible_default_ipv4.address}} {{item}}' state=present
  with_items: '{{groups.all}}'
  tags:
    - hosts
    
## se linux disable
- name: se linux disable
  command: sudo sed -i "s/SELINUXTYPE=targeted/SELINUX=permissive/" /etc/selinux/config
  

