---

- name: testing
  hosts: Standby
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: root

  tasks:  
  - name: debug
    debug:
      var: ansible_env.PATH
  
  - name: include role
    include_role:
      name: linux_postgres_db_setup_standby
