---

- name: create directory postgres & postgres_log
  file:
    path: /postgres/system/pgsql/etc/
    state: directory
    owner: postgres
    group: postgres
    mode: 0750

- name: Copy shellscript for repmgr user
  template:
    src: rep_user.j2
    dest: "/home/rep_user.sh"
    owner: postgres
    group: postgres
    mode: 'u=rwx,go=rx'


- name: execute the shell script for repmgr user
  command: sh /home/rep_user.sh
  environment:
    PATH: "/postgres/system/pgsql/bin:{{ ansible_env.PATH }}"
    PGDATA: "/pgdata/pgdata01"

- name: Create repmgr.conf in Standby
  template:
    src: repmgr.conf.j2
    dest: /postgres/system/pgsql/etc/repmgr.conf
    owner: postgres
    group: postgres
    mode: 0750
    force: yes

- name: Clone from Master
  become: yes
  become_user: postgres
  become_method: sudo
  shell: rm -rf /pgdata/pgdata01/ && repmgr -h {{ hostvars['localhost']['master'] }} -p 5432 -U repmgr -d repmgr -f /postgres/system/pgsql/etc/repmgr.conf standby clone
  environment:
    PATH: "/postgres/system/pgsql/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "/postgres/system/pgsql/lib:$LD_LIBRARY_PATH"

- name: Register As Standby
  become: yes
  become_user: postgres
  become_method: sudo
  shell: repmgr -f /postgres/system/pgsql/etc/repmgr.conf standby register
  environment:
    PATH: "/postgres/system/pgsql/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "/postgres/system/pgsql/lib:$LD_LIBRARY_PATH"


