---
# tasks file for linux_postgres_db_creation


- name: Ensure the PostgreSQL service is runnin
  service:
    name: postgresql
    state: started

- name: creation of database
  become: yes
  become_user: postgres
  command:     whoami
  register:    whoami

- debug: msg="{{whoami.stdout}}"

- name: creation of db
  postgresql_db:
    name: testdb

- name: Copy shellscript
  become: yes
  template:
    src: db.j2
    dest: "/home/db.sh"
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: execute the shell script
  command: sh /home/db.sh
  



