---
# tasks file for linux_postgres_db_creation


- name: Ensure the PostgreSQL service is runnin
  service:
    name: postgresql-9.6
    state: stopped

- replace:
    path: /var/lib/pgsql/9.6/data/pg_hba.conf
    regexp: 'peer'
    replace: 'trust'
    backup: yes

- name: Ensure the PostgreSQL service is runnin
  service:
    name: postgresql-9.6
    state: started

- name: creation of database
  become: yes
  become_user: postgres
  command:     whoami
  register:    whoami

- debug: msg="{{whoami.stdout}}"
#- name: shell command psql
#  shell: psql
#  become_user: postgres


- name: creation of db
  postgresql_db:
    name: testdb

- name: Copy shellscript
  become: yes
  template:
    src: db.j2
    dest: "/home/db.sh"
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: execute the shell script
  command: sudo sh /home/db.sh
  
#- name: shell command psql to create db and tables and values
#  shell: psql && \c Sample_BMW_DB && CREATE TABLE POC_BMW (id INTEGER PRIMARY KEY, name VARCHAR) && INSERT INTO POC_BMW VALUES (1,'ABC') 
#  become_user: postgres



